=begin	
	Get the average number from the log of govement site update
	TODO: Now ,all the logs were generated by the tester. Spider should should add a new feature to support it .
=end


def get_number(logfile)
	array = []
	File.open(logfile) do |file|
		file.each do |line|
			array<<(line.chop.split(":")[1])
		end
	end
	sum = 0
#	puts array.length
	array.each {|i| sum = sum +i.to_i}
	sum / array.length
end

def help()

	puts "Usage:ruby update_freq.rb your_freq_stat_file"

end

if ARGV.length != 1
	puts "You have wrong arg number!"
	help()
	exit	
end

puts get_number(ARGV[0])

