TARGET=../../../docs/admin.md
echo "**Do NOT update this file because it was generated by a script.**" > $TARGET
echo >>$TARGET
echo "Generated on `date`" >>$TARGET
find .. -name README.md -exec cat {} >>$TARGET \; -exec printf '\n\n' >>$TARGET \;
